apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: devoxxfr23-v2
  name: devoxxfr23-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: devoxxfr23-v2
      app.kubernetes.io/version: "2.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devoxxfr23-v2
        app.kubernetes.io/version: "2.0"
    spec:
      containers:
        - image: sebi2706/devoxxfr23:2.0
          imagePullPolicy: Always
          name: devoxxfr23-v2
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests: 
              memory: "300Mi" 
              cpu: "750m" # 10 cores
            limits:
              memory: "500Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
                port: 8080
                path: /health/live
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080

