apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: devoxxfr23
    app.kubernetes.io/version: "1.0"
  name: devoxxfr23
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: devoxxfr23
    app.kubernetes.io/version: "1.0"
  type: LoadBalancer