apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: devoxxfr23
  name: devoxxfr23
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devoxxfr23
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devoxxfr23
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - image: sebi2706/devoxxfr23:1.0
          imagePullPolicy: Always
          name: devoxxfr23
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: my-config
          resources:
            requests: 
              memory: "300Mi" 
              cpu: "750m" # 10 cores
            limits:
              memory: "500Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
                port: 8080
                path: /health/live
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080

